// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4pVIDWK4aQElKRTVAHGdNwjh_DhPirw',
    appId: '1:805358720744:web:88c50ac90aca87ab755b5d',
    messagingSenderId: '805358720744',
    projectId: 'garden-central-b8cbc',
    authDomain: 'garden-central-b8cbc.firebaseapp.com',
    storageBucket: 'garden-central-b8cbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbmt0LJpNYo3BGZJR27v4g4E7llePg6LU',
    appId: '1:805358720744:android:2d3da0e2e0e65177755b5d',
    messagingSenderId: '805358720744',
    projectId: 'garden-central-b8cbc',
    storageBucket: 'garden-central-b8cbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrArevmtr48sxC9aLtRlwBZxGqZvY90Io',
    appId: '1:805358720744:ios:61228734e0561308755b5d',
    messagingSenderId: '805358720744',
    projectId: 'garden-central-b8cbc',
    storageBucket: 'garden-central-b8cbc.appspot.com',
    iosClientId:
        '805358720744-h2nkcc6n057u1oj4a3kil4fuoegk1jlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenCentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrArevmtr48sxC9aLtRlwBZxGqZvY90Io',
    appId: '1:805358720744:ios:61228734e0561308755b5d',
    messagingSenderId: '805358720744',
    projectId: 'garden-central-b8cbc',
    storageBucket: 'garden-central-b8cbc.appspot.com',
    iosClientId:
        '805358720744-h2nkcc6n057u1oj4a3kil4fuoegk1jlb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gardenCentral',
  );
}
